server:
  port: 9232
resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration:
          nanos: 1000
        retry-exceptions:
          - com.resilience.resilienceservice.exception.RetryException
        ignore-exceptions:
          - com.resilience.resilienceservice.exception.IgnoreException
    instances:
      simpleRetryConfig:
        base-config: default

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 10
        failure-rate-threshold: 30
        slow-call-duration-threshold:
          nanos: 3000
        slow-call-rate-threshold: 50
        event-consumer-buffer-size: 10
        record-exceptions:
          - com.resilience.resilienceservice.exception.RecordException

